const chapters=[
{tag:'THE FIRST FRAME',title:'The day became beautiful',intro:'Jaanu, this first video is the little doorway into your birthday universe. Take a breath, press play, and let this moment belong only to you.',note:'Aaj ka din sirf calendar ki ek date nahi hai. Aaj woh din hai jab duniya ko tum jaisi khoobsurat rooh mili. Main chahta hoon ki tum khud ko utni hi pyaari nazar se dekho jitni pyaari tum mujhe lagti ho.'},
{tag:'A LITTLE MEMORY',title:'If moments could hug',intro:'Some memories are not stored in galleries; they stay quietly inside the heart. This chapter is for every small moment that became special because of you.',note:'Tumhare saath guzra hua chhota sa waqt bhi mere liye kisi bade celebration se kam nahi. Kabhi tumhari smile, kabhi tumhari baat, kabhi tumhara bina wajah naraz hona—sab kuch mere din ka favourite part ban jaata hai.'},
{tag:'THE REASONS',title:'Why you are my favourite',intro:'There are things I could list forever, but this video is only one small page from a much longer letter.',note:'Mujhe tumhari perfection nahi, tumhari asliiyat pasand hai. Tumhara khush hona, tumhara overthink karna, tumhara care karna, tumhara apne logon ke liye soft rehna—ye sab tumhe tum banata hai, aur mujhe tum bahut pasand ho.'},
{tag:'THE WISH',title:'A thousand soft wishes',intro:'Close your eyes for a second and imagine every good thing finding its way to you.',note:'Meri dua hai ki tumhari aankhon mein aansu aayein toh sirf khushi ke, tumhare dil par bojh ho toh jaldi halka ho, tumhare sapne tumse kabhi door na jaayein, aur tumhe har mod par aise log milein jo tumhari value samjhein.'},
{tag:'THE LITTLE PROMISE',title:'I will keep choosing care',intro:'Love is not only a grand sentence. Sometimes it is patience, listening, understanding, and showing up again.',note:'Main bade-bade promises se zyada chhoti-chhoti cheezon mein care dikhana chahta hoon. Tumhari baat sunna, tumhare mood ko samajhne ki koshish karna, galti ho toh ego se pehle sorry kehna, aur tumhe kabhi akela mehsoos na hone dena.'},
{tag:'THE FUTURE',title:'More birthdays, more stories',intro:'Imagine this chapter as a tiny postcard from all the birthdays we have yet to celebrate.',note:'Main chahta hoon ki aane wale saalon mein hum sirf birthdays wish na karein, balki naye memories banayein—random walks, simple dinners, silly arguments, long calls, unexpected gifts, aur woh moments jinke baare mein baad mein hum hans kar baat karein.'},
{tag:'THE SOFT PLACE',title:'You deserve gentle days',intro:'For every day when the world feels too loud, I hope this little page reminds you that you matter.',note:'Agar kabhi tumhe lage ki tum enough nahi ho, toh thoda ruk kar yaad karna: tumhari value kisi result, kisi opinion, kisi comparison ya kisi difficult day se decide nahi hoti. Tum apni jagah par precious ho.'},
{tag:'THE CELEBRATION',title:'Today, we celebrate you',intro:'Not only your birthday, but your courage, your growth, your laughter, and every version of you that reached this day.',note:'Tumne jitna face kiya, jitna seekha, jitna grow kiya—us sab ke liye I am proud of you. Aaj khud ko permission do khush hone ki, pamper hone ki, smile karne ki, aur bina guilt ke apna special day enjoy karne ki.'},
{tag:'THE HEART NOTE',title:'Read this slowly',intro:'This chapter is a pause. No rush. Let every line settle for a moment.',note:'Meri jaan, tum meri life ka sirf ek beautiful part nahi ho; tum un feelings mein se ho jinke liye words kabhi-kabhi chhote pad jaate hain. Main tumhe control nahi karna chahta, tumhe badalna nahi chahta—main tumhe samajhna, respect karna aur tumhari khushi mein genuinely khush rehna chahta hoon.'},
{tag:'THE FINAL DOOR',title:'The best is still unwritten',intro:'One last video before the birthday sky opens. Thank you for being you.',note:'Happy Birthday, meri jaanu. Tumhari life mein pyaar ho, peace ho, success ho, health ho, aur woh confidence ho jisse tum apne dreams ke peeche bina dare ja sako. Main chahta hoon tumhari smile kabhi kisi pressure ke neeche na dabey. Aaj aur hamesha—keep shining, keep growing, keep being wonderfully you.'}
];
let current=0,completed=new Set(),video=document.querySelector('#video'),source=document.querySelector('#videoSource');
const $=s=>document.querySelector(s);const screens=[...document.querySelectorAll('.screen')];
function show(id){screens.forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function musicStart(){const m=$('#music');m.play().catch(()=>toast('Tap the page once to start birthday music 🎵'))}
document.addEventListener('click',musicStart,{once:true});
$('[data-next]').onclick=()=>{show('gate');musicStart()};
$('#promiseCheck').onchange=e=>$('#unlock').disabled=!e.target.checked;
$('#unlock').onclick=()=>{show('journey');renderChapter()};
function renderDots(){const d=$('#dots');d.innerHTML='';chapters.forEach((_,i)=>{const x=document.createElement('span');x.className='dot'+(completed.has(i)?' done':'')+(i===current?' current':'');d.appendChild(x)})}
function renderChapter(){const c=chapters[current];$('#chapterNumber').textContent=String(current+1).padStart(2,'0')+' / 10';$('#chapterTag').textContent=c.tag;$('#chapterTitle').textContent=c.title;$('#chapterIntro').textContent=c.intro;$('#chapterNote').textContent=c.note;source.src='v'+(current+1)+'.mp4';video.load();$('#continue').disabled=true;$('#continue').textContent=current===9?'Open the birthday finale ✨':'Complete chapter →';$('#videoFallback').style.display='none';renderDots();$('#progressFill').style.width=((current)/10*100)+'%'}
video.addEventListener('error',()=>{$('#videoFallback').style.display='grid';$('#videoFallback').innerHTML='Add <strong>v'+(current+1)+'.mp4</strong> beside index.html to show this chapter.';toast('Video file missing: v'+(current+1)+'.mp4')});
video.addEventListener('ended',()=>{$('#continue').disabled=false;toast('Chapter complete 💙')});
$('#replay').onclick=()=>{video.currentTime=0;video.play().catch(()=>{});};
$('#continue').onclick=()=>{completed.add(current);if(current<9){current++;renderChapter()}else{show('finale');$('#progressFill').style.width='100%';$('#finalText').textContent='Meri jaanu, agar main tumhare liye duniya ki saari lights bhi jala doon, phir bhi tumhari smile jitni roshan koi cheez nahi hogi. Thank you for existing, for trying, for laughing, for being soft even when life is not. May this new year of your life bring you closer to yourself, your dreams, your peace and every beautiful thing you deserve. Happy Birthday, baby. You are loved, you are important, and you will always have a special place in my heart. 💙🌷💋';}}
$('#confettiBtn').onclick=()=>{for(let i=0;i<90;i++){const e=document.createElement('span');e.className='confetti';e.textContent=['💙','💋','🌷','✨','🎂','🎈','💫'][Math.floor(Math.random()*7)];e.style.left=Math.random()*100+'vw';e.style.animationDelay=Math.random()*1.5+'s';document.body.appendChild(e);setTimeout(()=>e.remove(),4500)}toast('Birthday sky unlocked ✨')};
$('#restart').onclick=()=>{current=0;completed.clear();show('journey');renderChapter()};
